"""changing

Revision ID: 64ba8f50647a
Revises: a64042833fd0
Create Date: 2022-05-22 13:55:19.300348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ba8f50647a'
down_revision = 'a64042833fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('scores', sa.Integer(), nullable=True))
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_column('post', 'timestamp')
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.add_column('post', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_column('post', 'scores')
    # ### end Alembic commands ###
