"""empty message

Revision ID: d087350e9fd7
Revises: 21785bd1889c
Create Date: 2022-05-22 22:17:07.283898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd087350e9fd7'
down_revision = '21785bd1889c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('post', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('post', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
