"""change post table

Revision ID: 21785bd1889c
Revises: 64ba8f50647a
Create Date: 2022-05-22 21:03:14.490233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21785bd1889c'
down_revision = '64ba8f50647a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_name', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_name'], ['username'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'user_name')
    # ### end Alembic commands ###
