"""empty message

Revision ID: 393acfb4ee67
Revises: f83a715a51da
Create Date: 2022-05-23 02:53:25.902007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393acfb4ee67'
down_revision = 'f83a715a51da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('post', 'id')
    op.drop_column('post', 'scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('scores', sa.INTEGER(), nullable=True))
    op.add_column('post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('post', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
