"""empty message

Revision ID: f83a715a51da
Revises: d087350e9fd7
Create Date: 2022-05-23 02:48:00.273672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83a715a51da'
down_revision = 'd087350e9fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('level1', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('level2', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('level3', sa.Integer(), nullable=True))
    op.alter_column('post', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('post', 'id')
    op.drop_column('post', 'scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('scores', sa.INTEGER(), nullable=True))
    op.add_column('post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('post', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('post', 'level3')
    op.drop_column('post', 'level2')
    op.drop_column('post', 'level1')
    # ### end Alembic commands ###
